name: nicolasfavre-icu metrics
on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: nicolasfavre-icu metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/bigass.svg
          user: nicolasfavre-icu
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_people: yes
          plugin_people_types: members
          plugin_repositories: yes
          plugin_traffic: yes
          plugin_skyline: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_lines: yes        